# Model Params
frontier_ckpt: "frontier_ckpt_new.ckpt"
traversability_ckpt: "traversability_ckpt.ckpt"
model_version: "c-radio_v3-b"
adaptor_version: null
use_naclip: true
use_summary_for_spatial: true
radio_dim: 768
static_scale_factor: 0.75
model_precision: "FP16"

# Nav Params
num_cameras: 3
cams_inverted: true

# Nav graph params
frontiers_range: 12.0
traversability_class: "default"

# Pixel Scoring Params
frontier_threshold: 0.6
frontier_opening_kernel_size: 20
traversability_threshold: 0.8
frontier_w: 2.0
goal_w: 3.0
reachability_w: 2.0
scoring_method: "MULTIPLICATIVE"
reach_scale: 0.25

# ROS2 frames and topics
parent_frame: "spot1/odom"
cam_frame: "spot1/realsense/{}_color_optical_frame"
camera_img_topic: "/spot1/realsense/{}/color/image_raw/compressed"
camera_info_topic: "/spot1/realsense/{}/color/camera_info"
odometry_topic: "/spot1/odom"
navigation_graph_topic: "/spot1/nav_graph"

# ROS2 Publisher topics
model_viz_topic: "/spot1/model_visualization"
valid_geofrontiers_topic: "/spot1/within_range_geofrontiers"

# ROS2 subscriber params
qos_history_depth: 1
syncsub_queue_size: 2
syncsub_slop: 0.2

# Goal Navigator Config
goal_navigator_config:
  # Nav
  goal_reach_radius: 2.0
  reach_in_2D: true
  waypoints: null
  overwrite_waypoints: true

  # ROS2
  waypoint_frame: "spot1/odom"
  waypoint_topic: "/spot1/imgnav_waypoint"
  waypoint_viz_topic: "/spot1/goal_waypoints"
  goal_dir_viz_topic: "/spot1/goal_direction"

# TFLookup Config
tf_lookup_config:
  buffer_size: 1
  cache_time: 10
  timer_duration: 0.1
  lookup_timeout: 0
  qos_history_depth: 1
  wait_for_oldest: true
  clear_buffer_on_process: true
  spin_thread: false
