# Model Params
frontier_ckpt: "frontier_head.ckpt"
traversability_ckpt: "trav_head.ckpt"
model_version: "c-radio_v3-b"
adaptor_version: null
use_naclip: true
use_summary_for_spatial: true
radio_dim: 768
static_scale_factor: 0.75
model_precision: "FP16"

# Nav Params
num_cameras: 3
cams_inverted: true

# Pixel Scoring Params
frontier_threshold: 0.6
frontier_opening_kernel_size: 20
traversability_threshold: 0.8
frontier_w: 2.0
goal_w: 3.0
reachability_w: 2.0
scoring_method: "MULTIPLICATIVE"
reach_scale: 0.25

# ROS2 frames and topics
parent_frame: "spot1/odom"
cam_frame: "spot1/realsense/{}_color_optical_frame"
camera_img_topic: "/spot1/realsense/{}/color/image_raw/compressed"
camera_depth_topic: "/spot1/realsense/{}/aligned_depth_to_color/image_raw"
camera_info_topic: "/spot1/realsense/{}/color/camera_info"
odometry_topic: "/spot1/odom"

# Publish topic names
model_viz_topic: "/spot1/model_visualization"
imgpath_topic: "/spot1/predicted_path"
nav2_goal_topic: "/spot1/goal_pose"

# ROS2 subscriber params
qos_history_depth: 1
syncsub_queue_size: 2
syncsub_slop: 0.2

# Object Search Config
object_search_config:
    text_queries: 
        - "orange flag"
    pixel_level_seg: true
    mask_threshold: 0.09
    obj_frontier_score: 0.9
    obj_trav_score: 0.9

# Goal Navigator Config
goal_navigator_config:
    # Nav
    goal_reach_radius: 2.0
    reach_in_2D: true
    waypoints: null
    overwrite_waypoints: true

    # ROS2
    waypoint_frame: "spot1/odom"
    waypoint_topic: "spot1/imgnav_waypoint"
    waypoint_viz_topic: "/spot1/goal_waypoints"
    goal_dir_viz_topic: "/spot1/goal_direction"

goal_lock_range: 6.0
path_max_depth: 5.0

# TFLookup Config
tf_lookup_config:
    buffer_size: 1
    cache_time: 10
    timer_duration: 0.1
    lookup_timeout: 0
    qos_history_depth: 1
    wait_for_oldest: true
    clear_buffer_on_process: true
    spin_thread: false
