# Model Params
frontier_ckpt: frontier_head.ckpt
traversability_ckpt: trav_head.ckpt
model_version: c-radio_v3-b
adaptor_version: null
use_naclip: true
use_summary_for_spatial: true
radio_dim: 768
static_scale_factor: 0.75
model_precision: FP16

# Nav Params
num_cameras: 3
cams_inverted: true
num_angular_bins: 16
reach_in_2D: true

# Nav graph params
frontiers_range: 9.0
traversability_class: default
heading_sim_thresh: 0.0
default_max_score: 0.3
std_for_default_scores: 80.0
std_for_frontier_heading: null
min_frontier_separation: 0.75

# Pixel Scoring Params
frontier_threshold: 0.6
frontier_opening_kernel_size: 20
traversability_threshold: 0.9
frontier_w: 2.0
goal_w: 3.0
reachability_w: 2.0
scoring_method: "MULTIPLICATIVE"
reach_scale: 0.25
compute_paths: true

# ROS2 frames and topics
parent_frame: spot1/odom
cam_frame: spot1/realsense/{}_color_optical_frame
camera_img_topic: /spot1/realsense/{}/color/image_raw/compressed
camera_info_topic: /spot1/realsense/{}/color/camera_info
odometry_topic: /spot1/odom
navigation_graph_topic: /spot1/nav_graph

# ROS2 Publisher topics
scored_navgraph_topic: /spot1/scored_nav_graph
model_viz_topic: /spot1/model_visualization
valid_geofrontiers_topic: /spot1/within_range_geofrontiers
score_ring_topic: /spot1/score_rings
graph_viz_topic: /spot1/nav_graph_viz

# ROS2 subscriber params
qos_history_depth: 1
syncsub_queue_size: 2
syncsub_slop: 0.2

# Object Search Config
object_search_config:
    text_queries:
        - "NASA logo"
    pixel_level_seg: false
    mask_threshold: 0.09
    obj_frontier_score: 0.9
    obj_trav_score: 0.9

# TFLookup Config
tf_lookup_config:
    buffer_size: 1
    cache_time: 10
    timer_duration: 0.1
    lookup_timeout: 0
    qos_history_depth: 1
    wait_for_oldest: true
    clear_buffer_on_process: true
    spin_thread: false
