graph_visualizer:
  ros__parameters:
    nav_graph_topic: /spot1/nav_graph
    odom_topic: /spot1/odom_for_scoring
    viz_topic: /spot1/graph_construction_viz
    show_radius_markers: false
    show_full_edges: false
    trajectory_min_separation: 0.25
    trajectory_max_points: 4000
