**
!nebula2-wildos/
!nebula2-wildos/dependencies/
!nebula2-wildos/dependencies/dlio.repos
!nebula2-wildos/docker/
!nebula2-wildos/docker/entrypoint.localization.sh
!nebula2-wildos/docker/healthcheck.localization.sh
!nebula2-wildos/graph_construction/
!nebula2-wildos/graph_construction/**

**/.git
**/.pytest_cache
**/__pycache__
**/*.egg-info
**/test
