class ObjectSearchState:
    """目标搜索状态名集中定义, 避免不同模块拼写分叉"""

    WAIT_FOR_ODOM = "WAIT_FOR_ODOM"
    TARGET_APPROACH_COARSE = "TARGET_APPROACH_COARSE"
    TARGET_APPROACH_METRIC = "TARGET_APPROACH_METRIC"
    TARGET_REACHED_VIEWPOINT = "TARGET_REACHED_VIEWPOINT"
    SEARCHING_WITH_INITIAL_GOAL = "SEARCHING_WITH_INITIAL_GOAL"
