input_topic: /elevation_mapping_node/elevation_map_raw
output_topic: /spot1/elevation_traversability_grid

traversability_layer: traversability
elevation_layer: elevation

free_threshold: 0.2
occupied_threshold: 0.05
unknown_value: -1
free_value: 0
occupied_value: 100

publish_rate_hz: 5.0
use_timer: false

normalize_traversability: true
normalize_low_quantile: 0.05
normalize_high_quantile: 0.95

enable_postprocess: true
min_free_component_cells: 25
fill_hole_max_cells: 90
fill_hole_min_free_neighbor_ratio: 0.65
majority_fill_iterations: 1
majority_fill_min_neighbors: 6

transpose: false
flip_x: false
flip_y: false
